export const asedaTemplates = {
  classicAseda: {
    id: 'classicAseda',
    name: 'Classic Aseda',
    description: 'Gold border, centered photo, formal serif text',
    style: {
      backgroundColor: '#FFFFFF',
      borderColor: '#C9A84C',
      borderWidth: 4,
      borderStyle: 'double',
      textColor: '#1a1a1a',
      nameColor: '#C9A84C',
      fontFamily: "'Playfair Display', Georgia, serif",
      bodyFontFamily: "'EB Garamond', Georgia, serif",
      photoShape: 'rounded',       // rounded, circle, square
      photoBorderColor: '#C9A84C',
      photoBorderWidth: 3,
      headerBg: 'transparent',
      accentColor: '#C9A84C',
      layout: 'centered',          // centered, left-photo, split
    },
  },
  kenteBorder: {
    id: 'kenteBorder',
    name: 'Kente Border',
    description: 'Kente-inspired geometric border pattern, bold text',
    style: {
      backgroundColor: '#FFF8E8',
      borderColor: '#D4A017',
      borderWidth: 0,
      borderStyle: 'none',
      textColor: '#2E1504',
      nameColor: '#D4A017',
      fontFamily: "'Playfair Display', Georgia, serif",
      bodyFontFamily: "'EB Garamond', Georgia, serif",
      photoShape: 'square',
      photoBorderColor: '#D4A017',
      photoBorderWidth: 3,
      headerBg: 'transparent',
      accentColor: '#C83030',
      layout: 'centered',
      kentePattern: true,
    },
  },
  royalMemorial: {
    id: 'royalMemorial',
    name: 'Royal Memorial',
    description: 'Dark background, white text, ornate frame around photo',
    style: {
      backgroundColor: '#0A0A0A',
      borderColor: '#C9A84C',
      borderWidth: 3,
      borderStyle: 'solid',
      textColor: '#E0E0E0',
      nameColor: '#C9A84C',
      fontFamily: "'Playfair Display', Georgia, serif",
      bodyFontFamily: "'EB Garamond', Georgia, serif",
      photoShape: 'circle',
      photoBorderColor: '#C9A84C',
      photoBorderWidth: 4,
      headerBg: 'rgba(201, 168, 76, 0.1)',
      accentColor: '#C9A84C',
      layout: 'centered',
    },
  },
  modernClean: {
    id: 'modernClean',
    name: 'Modern Clean',
    description: 'Minimalist, sans-serif, subtle gradient',
    style: {
      backgroundColor: '#F8F9FA',
      borderColor: '#D1D5DB',
      borderWidth: 1,
      borderStyle: 'solid',
      textColor: '#374151',
      nameColor: '#1F2937',
      fontFamily: "'Inter', 'Segoe UI', sans-serif",
      bodyFontFamily: "'Inter', 'Segoe UI', sans-serif",
      photoShape: 'rounded',
      photoBorderColor: '#9CA3AF',
      photoBorderWidth: 1,
      headerBg: 'transparent',
      accentColor: '#6B7280',
      layout: 'left-photo',
      gradient: 'linear-gradient(135deg, #F8F9FA 0%, #E5E7EB 100%)',
    },
  },
}

export const asedaDefaultDesign = {
  id: null,
  templateId: 'classicAseda',
  deceasedName: '',
  dateOfBirth: '',
  dateOfDeath: '',
  familyName: '',
  message: 'In Loving Memory',
  photo: null,
  backgroundColor: '#FFFFFF',
  createdAt: null,
  updatedAt: null,
}

export function getTemplateStyle(templateId) {
  return asedaTemplates[templateId]?.style || asedaTemplates.classicAseda.style
}
