export const oneWeekThemes = {
  burgundyGold: {
    name: 'Burgundy & Gold',
    description: 'Classic one-week burgundy with gold accents',
    layout: 'grand',
    headerBg: '#5C1A2A',
    bodyBg: '#4A1525',
    accent: '#D4AF37',
    detailsBg: '#3A0F1A',
    detailsText: '#FDF8F0',
    footerBg: '#2A0A12',
    headerText: '#D4AF37',
    nameText: '#D4AF37',
    bodyText: '#F0E0D0',
    divider: '#D4AF37',
    badgeBg: '#8B0000',
    badgeText: '#D4AF37',
    badgeBorder: '#D4AF37',
  },
  blackGold: {
    name: 'Black & Gold',
    description: 'Dramatic black with rich gold details',
    layout: 'grand',
    headerBg: '#0A0A0A',
    bodyBg: '#111111',
    accent: '#C9A84C',
    detailsBg: '#1A1A1A',
    detailsText: '#E0E0E0',
    footerBg: '#0A0A0A',
    headerText: '#C9A84C',
    nameText: '#C9A84C',
    bodyText: '#E0E0E0',
    divider: '#C9A84C',
    badgeBg: '#8B0000',
    badgeText: '#C9A84C',
    badgeBorder: '#C9A84C',
  },
  creamBurgundy: {
    name: 'Cream & Burgundy',
    description: 'Soft cream background with burgundy accents',
    layout: 'elegant',
    headerBg: '#FDF8F0',
    bodyBg: '#FAF5EB',
    accent: '#5C1A2A',
    detailsBg: '#5C1A2A',
    detailsText: '#FDF8F0',
    footerBg: '#3A0F1A',
    headerText: '#5C1A2A',
    nameText: '#5C1A2A',
    bodyText: '#3A2A1E',
    divider: '#D4AF37',
    badgeBg: '#D4AF37',
    badgeText: '#5C1A2A',
    badgeBorder: '#5C1A2A',
  },
  royalPurple: {
    name: 'Royal Purple',
    description: 'Regal purple with silver accents',
    layout: 'centered',
    headerBg: '#1E0A38',
    bodyBg: '#28104A',
    accent: '#C0C0C8',
    detailsBg: '#1E0A38',
    detailsText: '#E8E0F0',
    footerBg: '#140628',
    headerText: '#C0C0C8',
    nameText: '#C0C0C8',
    bodyText: '#E8E0F0',
    divider: '#C0C0C8',
    badgeBg: '#6A0DAD',
    badgeText: '#C0C0C8',
    badgeBorder: '#C0C0C8',
  },
  kenteGold: {
    name: 'Kente Gold',
    description: 'Bold Ashanti kente-inspired warmth',
    layout: 'heritage',
    headerBg: '#2E1504',
    bodyBg: '#3A1C08',
    accent: '#D4A017',
    detailsBg: '#2E1504',
    detailsText: '#FFF4D6',
    footerBg: '#1E0E02',
    headerText: '#F0D870',
    nameText: '#D4A017',
    bodyText: '#FFF4D6',
    divider: '#D4A017',
    badgeBg: '#C83030',
    badgeText: '#FFFFFF',
    badgeBorder: '#D4A017',
  },
  forestGold: {
    name: 'Forest & Gold',
    description: 'Peaceful nature-inspired green and gold',
    layout: 'centered',
    headerBg: '#1A3A2A',
    bodyBg: '#1A3A2A',
    accent: '#C9A84C',
    detailsBg: '#142E22',
    detailsText: '#E0F0E0',
    footerBg: '#0E2218',
    headerText: '#C9A84C',
    nameText: '#C9A84C',
    bodyText: '#E0F0E0',
    divider: '#C9A84C',
    badgeBg: '#C9A84C',
    badgeText: '#1A3A2A',
    badgeBorder: '#C9A84C',
  },
  navyGold: {
    name: 'Navy & Gold',
    description: 'Classic navy blue with gold accents',
    layout: 'elegant',
    headerBg: '#0A1628',
    bodyBg: '#0E1E38',
    accent: '#D4AF37',
    detailsBg: '#0A1628',
    detailsText: '#D8E8F0',
    footerBg: '#06101E',
    headerText: '#D4AF37',
    nameText: '#D4AF37',
    bodyText: '#D8E8F0',
    divider: '#D4AF37',
    badgeBg: '#D4AF37',
    badgeText: '#0A1628',
    badgeBorder: '#D4AF37',
  },
  rosePink: {
    name: 'Rose Pink',
    description: 'Soft, tender rose and blush tones',
    layout: 'heritage',
    headerBg: '#3A1020',
    bodyBg: '#4A1828',
    accent: '#D4A0A8',
    detailsBg: '#3A1020',
    detailsText: '#F8E0E5',
    footerBg: '#2A0A15',
    headerText: '#D4A0A8',
    nameText: '#D4A0A8',
    bodyText: '#F8E0E5',
    divider: '#D4A0A8',
    badgeBg: '#D4A0A8',
    badgeText: '#3A1020',
    badgeBorder: '#D4A0A8',
  },
}

export function getOneWeekTheme(key) {
  return oneWeekThemes[key] || oneWeekThemes.burgundyGold
}

export const oneWeekDefaultData = {
  theme: 'burgundyGold',
  headerTitle: 'ONE WEEK OBSERVATION',
  headerSubtitle: 'of the late',
  photo: null,
  archivePhoto: null,
  title: '',
  fullName: '',
  alias: '',
  age: '',
  eventDay: '',
  eventDate: '',
  venue: '',
  time: '',
  invitationText: 'ALL FRIENDS AND SYMPATHIZERS ARE CORDIALLY INVITED',
}
