export const themes = {
  blackGold: {
    name: 'Black & Gold',
    description: 'Classic funeral elegance',
    category: 'classic',
    pageBg: '#0A0A0A',
    secondaryBg: '#1A1A1A',
    gold: '#C9A84C',
    lightGold: '#E8D48B',
    paleGold: '#F0E6C0',
    cream: '#FAF6EE',
    offWhite: '#F5F0E8',
    heading: '#C9A84C',
    bodyText: '#FAF6EE',
    subtleText: '#E8D48B',
    border: '#C9A84C',
    accent: '#B8960F',
    placeholderBg: '#2A2520',
  },
  whiteNavy: {
    name: 'White & Navy Blue',
    description: 'Elegant and refined',
    category: 'classic',
    pageBg: '#FFFFFF',
    secondaryBg: '#F8F9FC',
    gold: '#8C8C8C',
    lightGold: '#B0B0B0',
    paleGold: '#E0E0E0',
    cream: '#2C3E6B',
    offWhite: '#1A2A4A',
    heading: '#1A2A4A',
    bodyText: '#2C3E6B',
    subtleText: '#5A6A8A',
    border: '#8C8C8C',
    accent: '#C0C0C0',
    placeholderBg: '#EEF0F5',
  },
  burgundyCream: {
    name: 'Burgundy & Cream',
    description: 'Warm and dignified',
    category: 'classic',
    pageBg: '#FDF8F0',
    secondaryBg: '#F5EDE0',
    gold: '#C9A84C',
    lightGold: '#D4B86A',
    paleGold: '#E8D48B',
    cream: '#4A1A2A',
    offWhite: '#3A0A1A',
    heading: '#6B1A2A',
    bodyText: '#4A1A2A',
    subtleText: '#7A3A4A',
    border: '#C9A84C',
    accent: '#8B1A2A',
    placeholderBg: '#F0E8DD',
  },
  emeraldSerenity: {
    name: 'Emerald Serenity',
    description: 'Peaceful green tranquility',
    category: 'premium',
    pageBg: '#0D1F17',
    secondaryBg: '#1A2E22',
    gold: '#7FB069',
    lightGold: '#A8D99C',
    paleGold: '#D4E8CD',
    cream: '#F0F5ED',
    offWhite: '#E8EFE5',
    heading: '#7FB069',
    bodyText: '#E8EFE5',
    subtleText: '#A8D99C',
    border: '#7FB069',
    accent: '#5A8F4E',
    placeholderBg: '#1A2E22',
  },
  royalPurple: {
    name: 'Royal Purple',
    description: 'Regal and distinguished',
    category: 'premium',
    pageBg: '#1A0F2E',
    secondaryBg: '#2A1F3E',
    gold: '#B8A9D4',
    lightGold: '#D4C8E8',
    paleGold: '#E8E0F0',
    cream: '#F5F0FA',
    offWhite: '#EDE8F5',
    heading: '#C4B5E0',
    bodyText: '#F0EBF7',
    subtleText: '#B8A9D4',
    border: '#9B8DC4',
    accent: '#7B6BA4',
    placeholderBg: '#2A1F3E',
  },
  oceanBlue: {
    name: 'Ocean Blue',
    description: 'Serene and calming',
    category: 'premium',
    pageBg: '#0A1628',
    secondaryBg: '#152238',
    gold: '#6B98C4',
    lightGold: '#8FB8D8',
    paleGold: '#C4D8E8',
    cream: '#EEF3F8',
    offWhite: '#E4ECF4',
    heading: '#7AA8D4',
    bodyText: '#E8F0F8',
    subtleText: '#8FB8D8',
    border: '#5A88B4',
    accent: '#4A78A4',
    placeholderBg: '#152238',
  },
  kenteGold: {
    name: 'Kente Gold',
    description: 'Bold Ghanaian heritage',
    category: 'premium',
    pageBg: '#1A1008',
    secondaryBg: '#2A1E12',
    gold: '#D4A017',
    lightGold: '#E8C040',
    paleGold: '#F0D870',
    cream: '#FFF8E8',
    offWhite: '#F8F0D8',
    heading: '#D4A017',
    bodyText: '#F8F0D8',
    subtleText: '#E8C040',
    border: '#D4A017',
    accent: '#C08A10',
    placeholderBg: '#2A1E12',
  },
  roseGarden: {
    name: 'Rose Garden',
    description: 'Soft and tender',
    category: 'premium',
    pageBg: '#1F1218',
    secondaryBg: '#2E1E25',
    gold: '#C4868F',
    lightGold: '#D8A0A8',
    paleGold: '#E8C0C5',
    cream: '#FDF0F2',
    offWhite: '#F8E8EB',
    heading: '#C4868F',
    bodyText: '#F8E8EB',
    subtleText: '#D8A0A8',
    border: '#B07078',
    accent: '#A06068',
    placeholderBg: '#2E1E25',
  },
  midnightSilver: {
    name: 'Midnight Silver',
    description: 'Sleek and modern',
    category: 'premium',
    pageBg: '#121418',
    secondaryBg: '#1E2028',
    gold: '#A8B0C0',
    lightGold: '#C0C8D4',
    paleGold: '#D8E0E8',
    cream: '#F0F2F5',
    offWhite: '#E8ECF0',
    heading: '#B0B8C8',
    bodyText: '#E8ECF0',
    subtleText: '#A0A8B8',
    border: '#808898',
    accent: '#707888',
    placeholderBg: '#1E2028',
  },
  kenteRoyal: {
    name: 'Kente Royal',
    description: 'Rich Ashanti kente weave colors',
    category: 'specialty',
    pageBg: '#1C0E04',
    secondaryBg: '#2E1A0C',
    gold: '#D4A017',
    lightGold: '#E8B830',
    paleGold: '#F0D060',
    cream: '#FFF4D6',
    offWhite: '#FAECC0',
    heading: '#C83030',
    bodyText: '#FFF4D6',
    subtleText: '#E8B830',
    border: '#D4A017',
    accent: '#1B6B3A',
    placeholderBg: '#2E1A0C',
  },
  militaryHonor: {
    name: 'Military Honor',
    description: 'Service & sacrifice',
    category: 'specialty',
    pageBg: '#0E1A10',
    secondaryBg: '#1A2E1C',
    gold: '#B8A04C',
    lightGold: '#D0BC6A',
    paleGold: '#E0D48A',
    cream: '#F5F2E8',
    offWhite: '#ECE8DA',
    heading: '#B8A04C',
    bodyText: '#ECE8DA',
    subtleText: '#D0BC6A',
    border: '#8A7A30',
    accent: '#3A5C2E',
    placeholderBg: '#1A2E1C',
  },
  sacredChurch: {
    name: 'Sacred Church',
    description: 'Holy & reverent',
    category: 'specialty',
    pageBg: '#FFFFF5',
    secondaryBg: '#F5F0E8',
    gold: '#8B7340',
    lightGold: '#A89060',
    paleGold: '#C8B88A',
    cream: '#3A1428',
    offWhite: '#2A0A18',
    heading: '#5C1030',
    bodyText: '#2A1020',
    subtleText: '#6A3050',
    border: '#8B7340',
    accent: '#7A1040',
    placeholderBg: '#EDE8DD',
  },
}

export const themeCategories = {
  all: 'All Themes',
  classic: 'Classic',
  premium: 'Premium',
  specialty: 'Specialty',
}

export function getTheme(themeKey) {
  return themes[themeKey] || themes.blackGold
}
