name = "funeralpress-ai-writer"
main = "brochure-ai-writer.js"
compatibility_date = "2026-04-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
ENVIRONMENT = "production"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "RATE_LIMITS"
id = "3cf6b47818c04ca8828461650478a6c1"

[[routes]]
pattern = "ai.funeralpress.org/*"
zone_name = "funeralpress.org"
