name = "brochure-share-api"
main = "share-api.js"
compatibility_date = "2026-04-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "BROCHURES_KV"
id = "25fef518037b4423a7176a0b4a533734"

[[routes]]
pattern = "share-api.funeralpress.org/*"
zone_name = "funeralpress.org"
